name: smart_shoper
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  easy_localization: ^3.0.0
  flutter_lints: ^1.0.0
  flutter_screenutil: ^5.4.0+1
  flutter_svg: ^1.0.3
  flutter_custom_clippers: ^2.0.0
  pin_code_fields: ^7.4.0
  stop_watch_timer: ^1.4.0
  card_swiper: ^2.0.3
  google_maps_flutter: ^2.1.4
  dotted_line: ^3.1.0
  modal_bottom_sheet: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1

  flutter_test:
    sdk: flutter
  google_fonts: ^2.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/
 
